### ISSUE TITLE
请问这个例子的代码报错怎么处理呢

### ISSUE THREAD

**Issue by Jsharkc** [hyjfine/flutter_redux_sample#1]
![image](https://user-images.githubusercontent.com/17465198/57788487-c44a8400-7769-11e9-85de-6655886861db.png)

**Comment by hyjfine** [comment]
fish redux appRoute重构了，用法要改下，我会尽快看下fish源码

**Comment by Jsharkc** [comment]
嗯嗯，感谢😁

**Comment by hyjfine** [comment]
已修复，请更新下代码
